### ISSUE TITLE
A small little bug

### ISSUE THREAD

**Issue by assaad** [joluet/okde-java-example#1]
Hello, please replace: 
z[i][j] = dist.evaluate(pointVector);
by 
z[j][i] = dist.evaluate(pointVector);

It took me a while to understand what is wrong with the plot :1234: 
Cheers :)
Assaad

**Comment by joluet** [comment]
Thank you for your feedback!

Shouldn't I rather replace

```
double[][] z = new double[y.length][x.length];
```

by

```
double[][] z = new double[x.length][y.length];
```

? I think that would be a proper fix. Because then `z[i][j]` would make more sense as `i` is the index of `x` and `j` is the index of `y`.

```
private double[][] evaluateSampleDistribution(double[] x, double[] y,
            BaseSampleDistribution dist) {
        double[][] z = new double[x.length][y.length];
        for (int i = 0; i < x.length; i++)
            for (int j = 0; j < y.length; j++) {
                double[][] point = { { x[i] }, { y[j] } };
                SimpleMatrix pointVector = new SimpleMatrix(point);
                z[i][j] = dist.evaluate(pointVector);
            }
        return z;
    }
```

**Comment by assaad** [comment]
Hello, the fix is as I proposed, because the z array should contain y then x so z[y][x]. 
Like in this code: 
https://code.google.com/p/jmathplot/wiki/GridPlotsExample https://code.google.com/p/jmathplot/wiki/GridPlotsExample
Where you can read: 
for (int i = 0; i < x.length; i++)
                        for (int j = 0; j < y.length; j++)
                                z[j][i] = f2(x[i], y[j]);
I tried it when I have x going from 0 to 24, and y from 0 to 1000 and I can see the difference. 
In your code both x and y goes to 10 so you can’t differentiate. 
Cheers!!
Assaad

**Comment by joluet** [comment]
Ok thank you for pointing to that example! That makes sense. I'll update the example then.
